"""SnowLuma 适配器（统一 QQ 连接器）共享常量。"""

SNOWLUMA_GATEWAY_NAME = "snowluma_gateway"
SUPPORTED_CONFIG_VERSION = "2.4.0"
DEFAULT_CLIENT_HOST = "127.0.0.1"
DEFAULT_CLIENT_PORT = 3001
DEFAULT_RECONNECT_DELAY_SEC = 5.0
DEFAULT_HEARTBEAT_INTERVAL_SEC = 30.0
DEFAULT_ACTION_TIMEOUT_SEC = 15.0
